# Generated by Django 5.1.7 on 2025-03-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0003_customuser_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(default='user', max_length=255),
        ),
    ]
