# Generated by Django 5.0.7 on 2025-03-28 12:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0010_alter_categories_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
