# Generated by Django 5.1.7 on 2025-03-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_code',
            field=models.CharField(default='random_code', max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_custom_code',
            field=models.CharField(default='SCT001', max_length=50, unique=True),
        ),
    ]
