# Generated by Django 5.1.7 on 2025-03-30 13:33

import django.utils.timezone
import invapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0002_alter_subcategory_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_code',
            field=models.CharField(default=invapp.models.generate_random_text, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_custom_code',
            field=models.CharField(default=invapp.models.get_subcategory_custom_code, max_length=50, unique=True),
        ),
    ]
