# Generated by Django 5.1.7 on 2025-03-24 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0004_user_delete_customeruser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
