# Generated by Django 5.0.7 on 2025-03-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0005_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_image'),
        ),
    ]
