# Generated by Django 5.1.7 on 2025-03-27 16:23

import invapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0008_categories_category_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='custom_code',
            field=models.CharField(default=invapp.models.generate_category_code, max_length=10, unique=True),
        ),
    ]
